require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe UploadUrlsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # UploadUrl. As you add validations to UploadUrl, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UploadUrlsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all upload_urls as @upload_urls" do
      upload_url = UploadUrl.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:upload_urls)).to eq([upload_url])
    end
  end

  describe "GET show" do
    it "assigns the requested upload_url as @upload_url" do
      upload_url = UploadUrl.create! valid_attributes
      get :show, {:id => upload_url.to_param}, valid_session
      expect(assigns(:upload_url)).to eq(upload_url)
    end
  end

  describe "GET new" do
    it "assigns a new upload_url as @upload_url" do
      get :new, {}, valid_session
      expect(assigns(:upload_url)).to be_a_new(UploadUrl)
    end
  end

  describe "GET edit" do
    it "assigns the requested upload_url as @upload_url" do
      upload_url = UploadUrl.create! valid_attributes
      get :edit, {:id => upload_url.to_param}, valid_session
      expect(assigns(:upload_url)).to eq(upload_url)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UploadUrl" do
        expect {
          post :create, {:upload_url => valid_attributes}, valid_session
        }.to change(UploadUrl, :count).by(1)
      end

      it "assigns a newly created upload_url as @upload_url" do
        post :create, {:upload_url => valid_attributes}, valid_session
        expect(assigns(:upload_url)).to be_a(UploadUrl)
        expect(assigns(:upload_url)).to be_persisted
      end

      it "redirects to the created upload_url" do
        post :create, {:upload_url => valid_attributes}, valid_session
        expect(response).to redirect_to(UploadUrl.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved upload_url as @upload_url" do
        post :create, {:upload_url => invalid_attributes}, valid_session
        expect(assigns(:upload_url)).to be_a_new(UploadUrl)
      end

      it "re-renders the 'new' template" do
        post :create, {:upload_url => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested upload_url" do
        upload_url = UploadUrl.create! valid_attributes
        put :update, {:id => upload_url.to_param, :upload_url => new_attributes}, valid_session
        upload_url.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested upload_url as @upload_url" do
        upload_url = UploadUrl.create! valid_attributes
        put :update, {:id => upload_url.to_param, :upload_url => valid_attributes}, valid_session
        expect(assigns(:upload_url)).to eq(upload_url)
      end

      it "redirects to the upload_url" do
        upload_url = UploadUrl.create! valid_attributes
        put :update, {:id => upload_url.to_param, :upload_url => valid_attributes}, valid_session
        expect(response).to redirect_to(upload_url)
      end
    end

    describe "with invalid params" do
      it "assigns the upload_url as @upload_url" do
        upload_url = UploadUrl.create! valid_attributes
        put :update, {:id => upload_url.to_param, :upload_url => invalid_attributes}, valid_session
        expect(assigns(:upload_url)).to eq(upload_url)
      end

      it "re-renders the 'edit' template" do
        upload_url = UploadUrl.create! valid_attributes
        put :update, {:id => upload_url.to_param, :upload_url => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested upload_url" do
      upload_url = UploadUrl.create! valid_attributes
      expect {
        delete :destroy, {:id => upload_url.to_param}, valid_session
      }.to change(UploadUrl, :count).by(-1)
    end

    it "redirects to the upload_urls list" do
      upload_url = UploadUrl.create! valid_attributes
      delete :destroy, {:id => upload_url.to_param}, valid_session
      expect(response).to redirect_to(upload_urls_url)
    end
  end

end
